congnv/blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index');

Route::resource('posts', 'PostsController');

congnv/blog/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'content'];
}

congnv/blog/app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Repositories\PostRepository;
use BiNet\App\Support\Pager;
use Hns\Core\Filters\PostFilter;
use Hns\Core\Services\PostService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class PostsController extends Controller
{
    private $service;

    public function __construct(PostService $service) {
        $this->service = $service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PostFilter $filter, Pager $pager)
    {   
        $items = $this->service->all($filter, $pager);
        dd($items);

        return view('posts.index', compact('items', 'filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $rules = [
            'title' => 'required|unique:posts|max:70',
            'content' => 'required',
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->passes()) {
            $item = new Post;
            $item->title = $request->get('title');
            $item->content = $request->get('content');

            if ($this->repo->save($item)) {
                \Session::flash('status', 'Created new item.');
                return redirect(route('posts.index'));
            }

            \Session::flash('status', 'This action cant be completed now. Pls retry later!');
            return redirect(route('posts.create'))->withInput();
        }

        return redirect(route('posts.create'))->withInput()->withErrors($validator);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = $this->repo->findOrFail($id);

        return view('posts.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $item = $this->repo->findOrFail($id);

        $rules = [
            'title' => 'required|unique:posts|max:70',
            'content' => 'required',
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->passes()) {
            $item->title = $request->get('title');
            $item->content = $request->get('content');

            if ($this->repo->save($item)) {
                \Session::flash('status', 'Updated post.');
                return redirect(route('posts.index'));
            }

            \Session::flash('status', 'This action cant be completed now. Pls retry later!');
            return redirect(route('posts.edit', $item->id))->withInput();
        }

        return redirect(route('posts.edit', $item->id))->withInput()->withErrors($validator);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = $this->repo->findOrFail($id);
        if ($this->repo->delete($item)) {
            \Session::flash('status', 'Data deleted!');
        } else {
            \Session::flash('status', 'This action cant be completed now. Pls retry later!');
        }

        return redirect(route('posts.index'));
    }
}

congnv/blog/app/Http/Controllers/_PostsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Repositories\PostRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class PostsController extends Controller
{
    private $repo;

    public function __construct(PostRepository $repo) {
        $this->repo = $repo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        $id = $request->get('id');
        $title = $request->get('title');
        $content = $request->get('content');

        $items = $this->repo->all($id, $title, $content);
        return view('posts.index', compact('items', 'id', 'title', 'content'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'title' => 'required|unique:posts|max:70',
            'content' => 'required',
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->passes()) {
            $item = new Post;
            $item->title = $request->get('title');
            $item->content = $request->get('content');

            if ($this->repo->save($item)) {
                \Session::flash('status', 'Created new item.');
                return redirect(route('posts.index'));
            }

            \Session::flash('status', 'This action cant be completed now. Pls retry later!');
            return redirect(route('posts.create'))->withInput();
        }

        return redirect(route('posts.create'))->withInput()->withErrors($validator);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = $this->repo->findOrFail($id);

        return view('posts.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $item = $this->repo->findOrFail($id);

        $rules = [
            'title' => 'required|unique:posts|max:70',
            'content' => 'required',
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->passes()) {
            $item->title = $request->get('title');
            $item->content = $request->get('content');

            if ($this->repo->save($item)) {
                \Session::flash('status', 'Updated post.');
                return redirect(route('posts.index'));
            }

            \Session::flash('status', 'This action cant be completed now. Pls retry later!');
            return redirect(route('posts.edit', $item->id))->withInput();
        }

        return redirect(route('posts.edit', $item->id))->withInput()->withErrors($validator);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = $this->repo->findOrFail($id);
        if ($this->repo->delete($item)) {
            \Session::flash('status', 'Data deleted!');
        } else {
            \Session::flash('status', 'This action cant be completed now. Pls retry later!');
        }

        return redirect(route('posts.index'));
    }
}

congnv/blog/resources/views/posts/create.blade.php
@extends('layouts.bootstrap')

@section('title', 'Create new user')
@section('content')
<form method="post" action="{{ route('posts.store') }}" class="form-horizontal">
	{{ csrf_field() }}
	<div class="form-group">
		<label for="title">Title:</label>
		<input type="text" name="title" value="{{ old('title') }}" id="title" class="form-control" />
		@if ($errors->has('title'))
		<p class="text-danger">{{ $errors->first('title') }}</p>
		@endif
	</div>
	<div class="form-group">
		<label for="content">Content:</label>
		<textarea name="content" id="content" class="form-control">{{ old('title') }}</textarea> 
		@if ($errors->has('content'))
		<p class="text-danger">{{ $errors->first('content') }}</p>
		@endif
	</div>
	<button type="submit" class="btn btn-default btn-primary">Submit</button>
</form>
@endsection

congnv/blog/resources/views/posts/edit.blade.php
@extends('layouts.bootstrap')

@section('title', 'Edit user')
@section('content')
<form method="post" action="{{ route('posts.update', $item->id) }}" class="form-horizontal">
	{{ csrf_field() }}
	{{ method_field('PUT') }}
	<div class="form-group">
		<label for="title">Title:</label>
		<input type="text" name="title" value="{{ old('title', $item->title) }}" id="title" class="form-control" />
		@if ($errors->has('title'))
		<p class="text-danger">{{ $errors->first('title') }}</p>
		@endif
	</div>
	<div class="form-group">
		<label for="content">Content:</label>
		<textarea name="content" id="content" class="form-control">{{ old('content', $item->content) }}</textarea> 
		@if ($errors->has('content'))
		<p class="text-danger">{{ $errors->first('content') }}</p>
		@endif
	</div>
	<button type="submit" class="btn btn-default btn-primary">Submit</button>
</form>
@endsection

congnv/blog/resources/views/posts/index.blade.php
@extends('layouts.bootstrap')

@section('title', 'User management')
@section('content')

@if (Session::has('status'))
<div class="alert alert-success alert-dismissable">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong>Success!</strong> {{ Session::pull('status') }}
</div>
@endif

<a href="{{ route('posts.create') }}" class="btn btn-success btn-sm">create</a>

<table class="table table-bordered table-striped table-hover">
	<tr>
		<th>id</th>
		<th>title</th>
		<th>content</th>
		<th>actions</th>
	</tr>
	<tr>
		<form method="get" class="form-inline">
			<td><input type="text" name="id" value="{{ $id }}" class="form-control" /></td>
			<td><input type="text" name="title" value="{{ $title }}" class="form-control" /></td>
			<td><input type="text" name="content" value="{{ $content }}" class="form-control" /></td>
			<td><input type="submit" class="btn btn-sm btn-success" value="Search" /></td>
		</form>
	</tr>
	@foreach($items as $item)
	<tr>
		<td>{{ $item->id }}</td>
		<td>{{ $item->title }}</td>
		<td>{{ $item->content }}</td>
		<td>
			<a href="{{ route('posts.edit', ['id' => $item->id]) }}" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i> edit</a>
			<form method="post" action="{{ route('posts.destroy', $item->id) }}">
				{{ csrf_field() }}
				{{ method_field('DELETE') }}
				<button type="submit" onclick="return confirm('Are you sure?');" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i> delete</button>
			</form>
		</td>
	</tr>
	@endforeach
</table>
@endsection